live_config_reload = true

[font]
size = 14

[font.bold]
family = "monospace"
style = "Bold"

[font.bold_italic]
family = "monospace"
style = "Bold Italic"

[font.italic]
family = "monospace"
style = "Italic"

[font.normal]
family = "monospace"
style = "Regular"

[window]
decorations = "None"
dynamic_padding = false
opacity = 0.8

[window.dimensions]
columns = 100
lines = 85

[window.padding]
x = 0
y = 0
